### ISSUE TITLE
it does not running one function

### ISSUE THREAD

**Issue by Abasit234** [pololu/qtr-sensors-arduino#10]
'QTRSensorsRC' does not name a type; did you mean 'QTRSensors'?

**Comment by DavidEGrayson** [comment]
The `QTRSensorsRC` class was removed in version 4.0.0 of this library, which was released on 2019-03-15.  If you have some old code that still uses that class, you might consider downgrading to version 3.1.0 of this library using the Arduino library manager.  Or you could look at the QTRRCExample example we include with the library to see updated code for RC-type sensors.

**Comment by Abasit234** [comment]
Thanks for helping it solves my problem
