### ISSUE TITLE
Read and set calibration value

### ISSUE THREAD

**Issue by Agents007** [pololu/qtr-sensors-arduino#11]

**Comment by DavidEGrayson** [comment]
see `calibrationOn` and `calibrationOff`

**Comment by Agents007** [comment]
Yes I know but how can I set the sensor value manually ?

Le mer. 3 mai 2023 à 17:48, David Grayson ***@***.***> a
écrit :

**Comment by DavidEGrayson** [comment]
What exactly do you mean?  What have you already tried and why did it not work?

**Comment by Agents007** [comment]
In my program I have to calibrate at each start. I want to do it only once
and then always use the same values. So to do this I need to get the
calibrationOn and calibrationOff values. After I get them how can I specify
them manually ?

Le mer. 3 mai 2023 à 17:57, David Grayson ***@***.***> a
écrit :

**Comment by DavidEGrayson** [comment]
First of all, look at the definition of `struct CalibrationData`  in QTRSensors.h so you know what data that struct contains.  Then use the C++ assignment operator (`=`) to set the values of each member.  For examples:

    sensors.calibrationOn.initialized = true;
    sensors.calibrationOn.minimum = your_array_of_minima;
    sensors.calibrationOn.maximum = your_array_of_maxima;

This seems like a general C++ programming question.  We use GitHub issues to keep track of bugs and feature requests in the library, so if you need more help the more appropriate place to ask would be:

https://forum.pololu.com

**Comment by DavidEGrayson** [comment]
Note: the destructor of QTRSensors uses `free` to free those arrays, so you should either allocate your arrays yourself with `malloc` or by calling `QTRSensors::calibrate` (and then overwriting the values it stores in the newly-allocated arrays).
