### ISSUE TITLE
Issue reading white line on black background

### ISSUE THREAD

**Issue by s1nisteR** [pololu/qtr-sensors-arduino#13]
I am having a issue where the readLineWhite() is not working properly. It keeps giving me values between 5000-6000 on a QTRX-13MD-RC, even though on a black line with readLineBlack() the readings are perfectly fine and gives me 0-12000.

readLineWhite() on a white line is causing issues.

**Comment by kevin-pololu** [comment]
It looks like you already started a [discussion](https://forum.pololu.com/t/issues-with-qtrx-reading-a-white-line/24856) about this on the Pololu forum, which is generally a better place for troubleshooting, so I'm closing this issue. If it does turn out to be a bug in the library itself, we can revisit the topic here.
