### ISSUE TITLE
Bug in QTRSensors::readLinePrivate()?

### ISSUE THREAD

**Issue by adamgreen** [pololu/qtr-sensors-arduino#14]
I think there might be a bug in the  QTRSensors::readLinePrivate() method. The weighted average is calculated in this method by the following code:
```c++
  for (uint8_t i = 0; i < _sensorCount; i++)
  {
...
    // only average in values that are above a noise threshold
    if (value > 50)
    {
      avg += (uint32_t)value * (i * 1000);
      sum += value;
    }
  }
...
  _lastPosition = avg / sum;
```

The ```i``` variable starts at 0 and that 0th element will always contribute a value of 0 to ```avg```.

Maybe something like this would work better?
```c++
  for (uint8_t i = 0; i < _sensorCount; i++)
  {
...
    // only average in values that are above a noise threshold
    if (value > 50)
    {
      avg += (uint32_t)value * ((i+1) * 1000);
      sum += value;
    }
  }
...
  _lastPosition = avg / sum - 1000;
```

It should still result in the same final range I think but the 0th element will always contribute to ```avg```.

Thoughts?

**Comment by kevin-pololu** [comment]
Hi, Adam.

It's true that the 0th element contributes 0 to `avg`, but it still affects the result because it changes `sum`. In any case, I think your formula works out to be equivalent to ours too.

**Comment by adamgreen** [comment]
Yes. I overlooked the part.

Sorry about that.
