### ISSUE TITLE
QTRSensors::calibrateOnOrOff Min/Max Value Storage

### ISSUE THREAD

**Issue by farzodd** [pololu/qtr-sensors-arduino#3]
Hi,

I was looking through your library, and I can't seem to figure out why you store the maximum value found during calibration into calibratedMinimum, and the minimum value into calibratedMaximum:

```
for(i=0;i<_numSensors;i++)
{
    if(min_sensor_values[i] > (*calibratedMaximum)[i])
        (*calibratedMaximum)[i] = min_sensor_values[i];
    if(max_sensor_values[i] < (*calibratedMinimum)[i])
        (*calibratedMinimum)[i] = max_sensor_values[i];
}
```

I keep trying to go through a step by step of how this would work, but I always end up with calibratedMinimum being larger than calibratedMaximum.  Should it be:

```
for(i=0;i<_numSensors;i++)
{
    if(max_sensor_values[i] > (*calibratedMaximum)[i])
        (*calibratedMaximum)[i] = max_sensor_values[i];
    if(min_sensor_values[i] < (*calibratedMinimum)[i])
        (*calibratedMinimum)[i] = min_sensor_values[i];
}
```

This is contained in line 230 to 236 of QTRSensors.cpp.

Thanks,
Farzad

**Comment by kevin-pololu** [comment]
Hi, Farzad.

The key point is that we store the maximum value found during calibration into `calibratedMinimum` _only if the maximum value is lower than `calibratedMinimum`_ (and vice versa for `calibratedMaximum`).

The `calibrateOnOrOff()` function takes 10 readings for each sensor and remembers the lowest of the 10 in `min_sensor_values`. If `min_sensor_values` is still greater than `calibratedMaximum`, then the function increases `calibratedMaximum` by setting it to `min_sensor_values`.

Keep in mind that the function is called many times in a loop.  By doing things this way, we make it less likely for outlying readings to affect the results. In other words, we will increase `calibratedMaximum` only if we get 10 readings in a row that are greater than it.

Kevin
