### ISSUE TITLE
Suggestion for all Pololu arduino libraries 

### ISSUE THREAD

**Issue by sebashb** [pololu/qtr-sensors-arduino#4]
Hi @kevin-pololu,
I have a suggestion to improve your arduino library.
The new arduino IDE includes a auto update of the libraries but for that it need’s a file called “library.properties” inside the library folder. I think that it would be good to add that file to all your libraries so that users can get always the newer versions automatically. I will attach a file the I made for the QTRSensors library base on an Adafruit library, I’m not sure if it works….  

``` Java
name=QTRSensors
version=2.1.2
author=Pololu
maintainer= Pololu <www.pololu.com>
sentence=Driver for Pololu QTR-XX line Sensors
paragraph=Driver for Pololu QTR-XX line Sensors
category=Sensors
url=hhttps://github.com/pololu/qtr-sensors-arduino
architectures=*
```

**Comment by ryantm** [comment]
@sebasqure Thanks for your suggestion. We are currently working on getting all of our libraries into the Library Manager, and this one is now in the Library Manager!
