### ISSUE TITLE
Invalid library 

### ISSUE THREAD

**Issue by MicMac11** [pololu/qtr-sensors-arduino#5]
Hello, I use Arduino 1.6.7 after adding the library QTR, this message appears : Invalid library found in Arduino \ libraries \ QT

**Comment by potus98** [comment]
Hi @MicMac11 
I once had similar issue in the past and found my problem was related to where I had stored the libraries on my local file system. Can you share the following details?
- Operating system, version
- IDE, version
- full path and file name of the local library
- Your Arduino code showing how the lib is being imported and used

Another thing that tripped me up one time: I had accidentally downloaded very similar QTR sensor libraries that were actually designed for Orangutan bots. Are you positive the library you obtained is for the Arduino boards?

Some additional notes that might be helpful. Excerpt from http://potus98.com/2012/10/24/demo-of-infrared-reflectance-array-with-arduino-mega/

Install Pololu QTR8A Libraries

Pololu QTR-8A Instructions for Arduino Note: There is a very similar looking set of instructions and libraries for Orangutan bots. Make sure to get the Arduino version.
Download Pololu QTR-8A Library
Extract the files and copy the QTRSensors folder into the ~/arduion-1.0.1/libraries folder.
Check the new library’s path and perms by importing within IDE: Sketch > Import Library > QTRSensors
Import within code: #include <QTRSensors.h>

**Comment by K-Mladen** [comment]
@MicMac11 Are you saving your project in the libraries folder?
Arduino/libraries is intended for libraries only, and having non-library
code in that folder would cause this message. If you move your
Arduino/libraries/QT folder (assuming this is a project) to Arduino/QT it
should work properly without the warning.

**Comment by ryantm** [comment]
Hi

Thanks for helping out @MicMac11. We use GitHub issues for fixing problems with the library code, and this doesn't sound like that kind of problem, so I'm closing it. If you need additional help installing or using the libraries, you can post on the [Pololu forum](http://forum.pololu.com), and we will be glad to help.

Ryan
